services:
  mongo:
    image: mongo:8.0.11
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongo-db:/data/db
    networks:
      - app-networks

  boot-app:
    image: aditya00707/chatback:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/chatapp
    depends_on:
      -  mongo
    networks:
      - app-networks



volumes:
  mongo-db:

networks:
  app-networks: